### ISSUE TITLE
Add config option for user whitelist

### ISSUE THREAD

**Issue by sminnee** [stojg/purr#1]
On an open-source project, all pull requests are equal, but some are more equal than others. It would be good if you could restrict this notification only to those PRs raised by other members of your team.

A whitelist of usernames would do this: when provided, only those PRs opened by or assigned to users in the whitelist would be shown.

**Comment by stojg** [comment]
Hi @sminnee,

Do you see any problem with your use case if the whitelist is globally across all repositories (including other git frontends, like gitlab)?

**Comment by sminnee** [comment]
Not really. You could always run purr a couple of times if you wanted different whitelists, and then you'd be able to post to different slack channels, etc, too.

**Comment by stojg** [comment]
planned for 0.3.0

**Comment by stojg** [comment]
Resolved in 0.3.0
