### ISSUE TITLE
Support wildcard search by organization

### ISSUE THREAD

**Issue by steveratay** [stojg/purr#20]
We are looking at integrating this library for our company, but it appears that using the wildcard search does not return private organizations.  In the config file, I am specifying the following:
```
"github_repos": [
    "<my org name>/*"
  ]
```

The following line of code appears to map to https://developer.github.com/v3/repos/#list-user-repositories, which only lists the public repos for a user.
```
		allRepos, _, err := client.Repositories.List(context.Background(), repoParts[0], nil)
```

It would be great if there were some way to be able to call `client.Repositories.ListByOrg`, which I believe will map to https://developer.github.com/v3/repos/#list-organization-repositories.

This would allow us to use this library to access our company's private GitHub repositories.

I'm not a Go developer so hesitant to submit a PR for this, plus I'm not sure how you would ideally like to segregate the user search from the org search in the configuration.  Please let me know if this is something you would consider changing, or if I'm just missing the proper way to perform an organization repository search.  Thanks!

**Comment by stojg** [comment]
Thanks for taking the time and getting me notified about this bug!
If you haven't found another solution, I've just released https://github.com/stojg/purr/releases/tag/0.6.0 with a changed configuration format that allows you to list all public and private PRs for an organisation.
