### ISSUE TITLE
Duplicate repositories in purr configuration show duplicate results in Slack

### ISSUE THREAD

**Issue by robbieaverill** [stojg/purr#22]
This is super minor, but our team has 60 or so repos in our config and I added one twice by accident.

This showed the open pull request on that repo twice in Slack:

![image](https://user-images.githubusercontent.com/5170590/33684045-b9269bde-db31-11e7-93eb-0e3e494aa94e.png)

Maybe a "filter for unique" pass could be run over the results before it's finished processing them?

**Comment by stojg** [comment]
Hah, I’ve had the same problem recently. Yeah, it makes total sense.

**Comment by stojg** [comment]
Fixed in https://github.com/stojg/purr/releases/tag/0.7.0
