### ISSUE TITLE
Support filtering draft PRs

### ISSUE THREAD

**Issue by ScopeyNZ** [stojg/purr#25]
The upstream GitHub go dependency has been updated to show draft state on PR:

https://godoc.org/github.com/google/go-github/github#PullRequest

It'd be great if the `filters` section would include filtering by that draft boolean.

**Comment by stojg** [comment]
Thanks for the notice!

This has been fixed in release https://github.com/stojg/purr/releases/tag/0.9.0 by filtering GH draft pull requests when the WIP filter is enabled.
