### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by luizs81** [stojg/purr#7]
Hey Stig, 

I'm sorry if this is silly, but I'm getting the following errors when trying to build. Any idea?
Thanks in advance!

```
./main.go:114: not enough arguments in call to client.Repositories.List
./main.go:153: not enough arguments in call to client.PullRequests.List
```

**Comment by stojg** [comment]
Sorry for not seeing this until now, I've totally forgotten to enable notifications. This might have been related to getting a different version of the API libraries. 

I have in the latest master branch committed the libraries into a vendor directory to ensure that builds are reproducible.
